export { default as GetStartedBlock } from './GetStartedBlock'
export { default as SupportersBlock } from './SupportersBlock'
export { default as FixTechBlock } from './FixTechBlock'
export { default as DiscountBlock } from './DiscountBlock'
export { default as WorkingProcessBlock } from './WorkingProcessBlock'
